export const KHR_RATE = 4050; // 1 USD = 4,050 KHR

export const THEME_PALETTE = [
  '#e8834a', // Brand Orange
  '#f09b68', // Light Peach Orange
  '#b85822', // Deep Amber Terracotta
  '#f7b78f', // Soft Warm Apricot
  '#d9733a', // Warm Tangerine
  '#f59e0b', // Amber
  '#fb923c', // Bright Orange
  '#ea580c', // Burnt Orange
  '#e11d48', // Warm Rose
  '#d97706', // Ochre
  '#a16207', // Bronze
  '#71717a'  // Neutral Zinc Slate
];

export const DEFAULT_CATEGORIES = {
  'Housing & Rent': { limit: 500, color: '#e8834a', nameEn: 'Housing & Rent', nameZh: '住房与房租' },
  'Dining & Food':  { limit: 300, color: '#f09b68', nameEn: 'Dining & Food', nameZh: '餐饮美食' },
  'Tech & Cloud':   { limit: 180, color: '#b85822', nameEn: 'Tech & Cloud', nameZh: '数码与云服务' },
  'Utilities':      { limit: 150, color: '#f7b78f', nameEn: 'Utilities', nameZh: '水电杂费' },
  'Transport':      { limit: 80,  color: '#71717a', nameEn: 'Transport', nameZh: '交通出行' }
};

export const BANK_CHANNELS = [
  'Cash',
  'ABA Bank',
  'ACLEDA Bank',
  'Bakong / KHQR',
  'Canadia Bank',
  'Wing Bank',
  'Sathapana Bank',
  'Chip Mong Bank',
  'Prince Bank',
  'Vattanac Bank',
  'J Trust Royal Bank',
  'Phillip Bank',
  'PPCBank',
  'CPBank',
  'Shinhan Bank',
  'BRED Bank'
];

export const I18N = {
  en: {
    badge_privacy: "local-first • zero-login",
    header_sub: "Privacy-focused ledger • 1 USD = 4,050 KHR • Local storage",
    btn_sync: "Sync Phone",
    btn_ai_schema: "AI Schema",
    kpi_total_spend: "TOTAL SPEND (MTD)",
    kpi_envelope_cap: "MONTHLY ENVELOPE CAP",
    btn_set_edit: "Set / Edit",
    kpi_cap_sub: "Sum of active envelopes",
    kpi_cushion: "REMAINING CUSHION",
    kpi_eom: "End of Month",
    kpi_status_ok: "Pacing within planned parameters",
    kpi_status_warn: "Warning: Monthly envelope exceeded!",
    cat_section_title: "Category Envelopes & Spending Caps",
    cat_section_sub: "Customize category targets or add envelopes to calibrate your total monthly cap.",
    btn_new_envelope: "New Envelope",
    lbl_cat_name_en: "NAME (EN)",
    lbl_cat_name_zh: "NAME (中文) - OPTIONAL",
    placeholder_cat_name_en: "e.g. Subscriptions",
    placeholder_cat_name_zh: "e.g. 订阅会员",
    err_cat_name_req: "Please enter at least one category name (EN or 中文)",
    lbl_cat_cap: "MONTHLY CAP ($ USD)",
    lbl_cat_color: "THEME ACCENT",
    btn_next_auto_color: "Auto",
    btn_save_envelope: "Save Envelope",
    btn_cancel: "Cancel",
    lbl_amount: "AMOUNT",
    lbl_category: "CATEGORY",
    lbl_channel: "PAYMENT CHANNEL",
    lbl_note: "NOTE / MERCHANT",
    placeholder_note: "e.g. Coffee, AWS, Groceries",
    lbl_recurring: "Recurring",
    btn_log_spend: "Log Spend",
    chart_donut_title: "Category Allocation",
    chart_donut_sub: "Prorated distribution with rounded segments",
    btn_refresh: "Refresh",
    lbl_total_spend: "Total Spend",
    chart_velocity_title: "Daily Spend Burn Velocity",
    chart_velocity_sub: "Cash outflow pacing & abnormal spike detection",
    badge_realtime_curve: "Real-time Curve",
    lbl_baseline_30d: "Baseline: 30-Day Velocity",
    velocity_monitoring: "Monitoring daily burn pace",
    velocity_empty: "No transactions recorded this month",
    ledger_title: "Local Ledger Records",
    ledger_sub: "IndexedDB / Local-First: Active on this device",
    ledger_empty: "No transactions logged yet. Use the form above to log your first spend.",
    donut_empty_legend: "No category spending recorded yet",
    th_date: "Date",
    th_category: "Category",
    th_note: "Note / Merchant",
    th_channel: "Channel",
    th_amount: "Amount",
    th_action: "Action",
    modal_cap_title: "Adjust Monthly Envelopes",
    modal_cap_sub: "Set the spending limits for each category to configure your total monthly cap.",
    lbl_total_monthly_cap: "TOTAL MONTHLY CAP:",
    btn_save_apply: "Save & Apply Changes",
    modal_single_title: "Edit Envelope Cap",
    lbl_new_monthly_limit: "NEW MONTHLY LIMIT ($ USD)",
    btn_update_limit: "Update Limit",
    modal_sync_title: "Sync Phone with PC",
    modal_sync_sub: "Direct WebRTC peer-to-peer pairing",
    sync_step_1: "1. Open Budget Lens on your phone",
    sync_step_2: "2. Scan this QR code to connect directly",
    lbl_session_id: "Session ID:",
    btn_close: "Close",
    of_cap: "of cap",
    cap_prefix: "Cap:",
    envelopes_label: "Envelopes",
    envelope_single: "Envelope",
    records_label: "Records",
    general_spend: "General Spend",
    err_min_khr: "Minimum amount is 100 ៛",
    err_min_usd: "Minimum amount is $0.01"
  },
  zh: {
    badge_privacy: "本地优先 • 免登录",
    header_sub: "专注隐私的本地账本 • 1 USD = 4,050 KHR • 本地化存储",
    btn_sync: "手机同步",
    btn_ai_schema: "AI 架构",
    kpi_total_spend: "本月总支出 (MTD)",
    kpi_envelope_cap: "每月信封预算上限",
    btn_set_edit: "设置 / 编辑",
    kpi_cap_sub: "各信封限额总和",
    kpi_cushion: "剩余预算缓冲",
    kpi_eom: "月末结余",
    kpi_status_ok: "支出节奏处于规划范围之内",
    kpi_status_warn: "警告：本月支出已超出信封上限！",
    cat_section_title: "分类信封与支出上限",
    cat_section_sub: "自定义各分类限额或新建信封，以校准每月总支出预算。",
    btn_new_envelope: "新建信封",
    lbl_cat_name_en: "分类名称 (英文)",
    lbl_cat_name_zh: "分类名称 (中文) - 可选",
    placeholder_cat_name_en: "如：Subscriptions",
    placeholder_cat_name_zh: "如：订阅会员",
    err_cat_name_req: "请至少填写一个分类名称（英文或中文）",
    lbl_cat_cap: "每月上限 ($ USD)",
    lbl_cat_color: "主题色",
    btn_next_auto_color: "自动推荐",
    btn_save_envelope: "保存信封",
    btn_cancel: "取消",
    lbl_amount: "金额",
    lbl_category: "分类",
    lbl_channel: "支付渠道",
    lbl_note: "备注 / 商家",
    placeholder_note: "如：咖啡、云服务器、日常采购",
    lbl_recurring: "周期性固定支出",
    btn_log_spend: "记录支出",
    chart_donut_title: "支出分类占比",
    chart_donut_sub: "圆角环形图分布统计",
    btn_refresh: "刷新",
    lbl_total_spend: "总支出",
    chart_velocity_title: "每日支出流出速率",
    chart_velocity_sub: "资金流出节奏与异常消费峰值监测",
    badge_realtime_curve: "实时曲线",
    lbl_baseline_30d: "30日流出基准",
    velocity_monitoring: "正在实时监测支出速率",
    velocity_empty: "本月暂无任何支出流水记录",
    ledger_title: "本地账本明细",
    ledger_sub: "IndexedDB / 本地优先：当前设备实时存储",
    ledger_empty: "暂无支出记录。请在上方输入框记录您的第一笔开销。",
    donut_empty_legend: "本月各信封暂无消费明细",
    th_date: "日期",
    th_category: "分类",
    th_note: "备注 / 商家",
    th_channel: "渠道",
    th_amount: "金额",
    th_action: "操作",
    modal_cap_title: "调整每月信封限额",
    modal_cap_sub: "分别调整各信封限额以更新月度总预算。",
    lbl_total_monthly_cap: "每月总上限：",
    btn_save_apply: "保存并应用更改",
    modal_single_title: "编辑信封限额",
    lbl_new_monthly_limit: "新月度限额 ($ USD)",
    btn_update_limit: "更新限额",
    modal_sync_title: "手机与电脑同步",
    modal_sync_sub: "点对点 WebRTC 安全直连配对",
    sync_step_1: "1. 在手机浏览器中打开 Budget Lens",
    sync_step_2: "2. 使用手机扫描此二维码建立实时直连",
    lbl_session_id: "会话编号:",
    btn_close: "关闭",
    of_cap: "的上限",
    cap_prefix: "上限:",
    envelopes_label: "个信封",
    envelope_single: "个信封",
    records_label: "条记录",
    general_spend: "日常支出",
    err_min_khr: "最低金额为 100 ៛",
    err_min_usd: "最低金额为 $0.01"
  }
};